package mysql;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.Time;
import java.util.List;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/access") // This means URL's start with /demo (after Application path)
public class MainController {
    private static SessionFactory factory;
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final StudentRepository studentRepository;
    private final CourseRepository courseRepository;

    @Autowired
    public MainController(StudentRepository studentRepository, CourseRepository courseRepository) {
        this.studentRepository = studentRepository;
        this.courseRepository = courseRepository;
        factory = new Configuration().configure().buildSessionFactory();
    }

    @GetMapping(path = "/addRecord") // Map ONLY GET Requests
    public @ResponseBody
    boolean addNewStudent(@RequestParam String first_name,
                          @RequestParam String last_name,
                          @RequestParam String email,
                          @RequestParam String course_ID,
                          @RequestParam String Student_ID,
                          @RequestParam String Android_ID,
                          @RequestParam String IMEI,
                          @RequestParam String course_name,
                          @RequestParam String start_hour,
                          @RequestParam String start_min,
                          @RequestParam String end_hour,
                          @RequestParam String end_min,
                          @RequestParam String course_day) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if (first_name.length() == 0) {
            throw new IllegalArgumentException("The 'first_name' parameter must not be null or empty");
        }
        Student_table n = new Student_table();
        Course_table c = new Course_table();
        c.setCourse_ID(course_ID);
        c.setCourse_name(course_name);
        c.setDay(course_day);
        c.setStart_time(Time.valueOf(start_hour + ":" + start_min + ":" + "00"));
        c.setEnd_time(Time.valueOf(end_hour + ":" + end_min + ":" + "00"));
        n.setAndroid_ID(Android_ID);
        n.setStudent_ID(Student_ID);
        n.setIMEI(IMEI);
        n.setFirst_name(first_name);
        n.setLast_name(last_name);
        n.setEmail(email);
        n.setCourse(c);

        studentRepository.save(n);
        return true;
    }


    @ExceptionHandler(IllegalArgumentException.class)
    void handleIllegalArgumentException(HttpServletResponse response) throws IOException {
        response.sendError(HttpStatus.BAD_REQUEST.value());
    }

    @GetMapping(path = "/allStudents")
    public @ResponseBody
    Iterable<Student_table> getAllStudents() {
        // This returns a JSON or XML with the users
        return studentRepository.findAll();
    }

    @GetMapping(path = "/allCourses")
    public @ResponseBody
    Iterable<Course_table> getAllCourses() {
        // This returns a JSON or XML with the users
        return courseRepository.findAll();
    }

    @GetMapping(path = "/studentCourses")
    public @ResponseBody
    Course_table[] getStudentCourses(@RequestParam String ID) {

        Session session = factory.openSession();
        /*Student_table student_table = (Student_table) session.get(Student_table.class, Student_ID) ;
        session.flush();
        session.close();
        */
        String hql = "FROM Course_table where ID in (select course.id FROM Student_table where Student_ID = :ID)";
        Query query = session.createQuery(hql);
        query.setParameter("ID", ID);
        List l = query.list();
        Course_table[] c = new Course_table[l.size()];
        for(int i=0;i<l.size();i++)
            c[i]=(Course_table)l.get(i);
        return c;
    }

    @GetMapping(path = "/ping")
    public @ResponseBody
    int sendPing(@RequestParam String ID) {
/*
        Session session = factory.openSession();
        //Student_table student_table = (Student_table) session.get(Student_table.class, Student_ID) ;
        //session.flush();
        //session.close();

        String hql = "FROM Course_table where ID in (select course.id FROM Student_table where Student_ID = :ID)";
        Query query = session.createQuery(hql);
        query.setParameter("ID", ID);
        return query.list();
*/
        return 1;
    }
}